import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Container from "./components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const orbitronFont = localFont({
  src: [
    {
      path: "../public/fonts/Orbitron-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/Orbitron-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/Orbitron-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../public/fonts/Orbitron-Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/Orbitron-ExtraBold.ttf",
      weight: "800",
    },
    {
      path: "../public/fonts/Orbitron-Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-orbitron",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbitronFont.variable} font-orbitron`}>
        <Container>{children}</Container>
        </body>
    </html>
  );
}
